### ISSUE TITLE
Unexpected ID with value 'user'.

### ISSUE THREAD

**Issue by mcastillo86** [dropbox/dropbox-sdk-java#128]
I've downloaded master and tried this command "./gradlew build" but I got the following error: **Unexpected ID with value 'user'.**

Error: 
```
Set JDK6_HOME environment to disable boot classpath warnings.
:generateStoneError(s) in route filter:
Unexpected ID with value 'user'.
 FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Work\dropbox-sdk-java\dropbox-sdk-java\stone.gradle' line: 72

* What went wrong:
Execution failed for task ':generateStone'.
> Process 'command 'python'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':generateStone'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.process.internal.ExecException: Process 'command 'python'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:367)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:31)
        at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:176)
        at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:856)
        at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:852)
        at org.gradle.api.Project$exec$0.call(Unknown Source)
        at stone_48a99ur2mfsd2sjwqjwcfw41s.runStoneGenerator(C:\Work\dropbox-sdk-java\dropbox-sdk-java\stone.gradle:72)
        at org.gradle.internal.metaobject.BeanDynamicObject$GroovyObjectAdapter.invokeOpaqueMethod(BeanDynamicObject.java:440)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:397)
        at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:169)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:80)
        at stone_48a99ur2mfsd2sjwqjwcfw41s$_run_closure1$_closure8$_closure14.doCall(C:\Work\dropbox-sdk-java\dropbox-sdk-java\stone.gradle:135)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 60 more


BUILD FAILED

Total time: 3.264 secs
```

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by alwaysrejoice** [comment]
I got similar error when I type ./gradlew install
can I run the android sample directly without installing gradlew?


> Configure project :
Set JDK6_HOME environment to disable boot classpath warnings.

> Task :generateStone
error: Importing generator '/Users/hui-jou/Documents/microdysis/dropbox-sdk-java/generator/java.stoneg.py' module raised an exception:
Traceback (most recent call last):
  File "/Users/hui-jou/anaconda/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/hui-jou/anaconda/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/hui-jou/Documents/microdysis/dropbox-sdk-java/stone/stone/cli.py", line 357, in <module>
    api = main()
  File "/Users/hui-jou/Documents/microdysis/dropbox-sdk-java/stone/stone/cli.py", line 328, in main
    generator_module = imp.load_source('user_generator', args.generator)
  File "/Users/hui-jou/anaconda/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/hui-jou/Documents/microdysis/dropbox-sdk-java/generator/java.stoneg.py", line 55, in <module>
    StoneType.register(ApiNamespace)
AttributeError: type object 'StoneType' has no attribute 'register'


FAILURE: Build failed with an exception.

* Where:
Script '/Users/hui-jou/Documents/microdysis/dropbox-sdk-java/stone.gradle' line: 72

* What went wrong:
Execution failed for task ':generateStone'.
> Process 'command 'python'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 2s
1 actionable task: 1 executed

**Comment by cakoose** [comment]
Can you try running `./update-submodules` and then running the build again?

**Comment by alwaysrejoice** [comment]
I have run  ./update-submodules and 
sudo -H python -m pip install ply six typing

and then I got the above error

**Comment by cakoose** [comment]
Oh, looks like the Java code generator ("generator/java.stoneg.py") is using Python 2 syntax that doesn't work in Python 3:

```
class StoneType:
    __metaclass__ = abc.ABCMeta
```

This should be changed to:

```
@six.add_metaclass(abc.ABCMeta)
class StoneType:
    pass
```

**Comment by cakoose** [comment]
@braincore: There's a bunch of

```
__metaclass__ = ...
```

in the Stone codebase as well.  Those should probably be changed to the 2/3-compatible syntax.

**Comment by alwaysrejoice** [comment]
when I apply dropbox API v2 in my android app, do I  need to initialize authentication session like API v1? I was referring to  this website https://www.dropbox.com/developers-v1/core/start/android, but I found some bug there, so I am trying to switch to API v2. But now I have trouble to understand how it work? it looks like a lot different from API v1.

**Comment by greg-db** [comment]
Thanks for the report @alwaysrejoice , and thanks for the help @cakoose !

@alwaysrejoice API v1 is deprecated and being retired soon, so you definitely will need to move to API v2 instead. The Dropbox API v2 SDK does work entirely differently than API v1. You can find everything you need to get started in the documentation here:

https://github.com/dropbox/dropbox-sdk-java

We recommend using Maven or Gradle so that you don't have to build from source as you were trying:

https://github.com/dropbox/dropbox-sdk-java#setup

For Android in particular, there's a sample app that shows how to set it up here:

https://github.com/dropbox/dropbox-sdk-java/tree/master/examples/android
