### ISSUE TITLE
NoSuchMethodError in StoneSerializer class, line 118

### ISSUE THREAD

**Issue by shuson** [dropbox/dropbox-sdk-java#145]
Hi developers, I came across this issue by executing following code：
```java
ListFolderResult result = client.files().listFolderBuilder("/folder_not_exists").start();
```
Expect it throwing 404 NOT_FOUND kind of DbxException. But it throws:

```
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonToken.isStructStart()Z
at com.dropbox.core.stone.StoneSerializer.skipValue(StoneSerializer.java:118)
at com.dropbox.core.ApiErrorResponse$Serializer.deserialize(ApiErrorResponse.java:62)
...
at com.dropbox.core.v2.files.DbxUserFilesRequests.listFolder(DbxUserFilesRequests.java:1075)
at com.dropbox.core.v2.files.ListFolderBuilder.start(ListFolderBuilder.java:109)
```

The SDK version is 3.0.3. FYI, 2.1.2 also has this error.

**Comment by jiuyangzhao** [comment]
Hey are you using maven or gradle to manage your dependency? I've seen some people having similar problem if they directly use .jar file and caused some version conflict in their project.

**Comment by shuson** [comment]
Hi, thanks for your reply.
I directly use jar file of sdk. If so. Let me try it using maven.
Thanks again for releasing new version 3.0.4.

**Comment by handstandsam** [comment]
Closing due to inactivity.  Please reopen if the issue exists in the 5.x versions.
