### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Aiuspaktyn** [dropbox/dropbox-sdk-java#147]
```
Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at com.dropbox.core.android.DbxOfficialAppConnector.getDropboxAppPackage(Unknown Source)
       at com.dropbox.core.android.AuthActivity$3.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by greg-db** [comment]
Thanks for the post! We'll be happy to look into this, but we'll need some more information. Please reply with:
- the steps to reproduce the issue
- the relevant code
- the version of Java/Android that you're see this with
- the version of the Dropbox Java SDK you're using

Thanks in advance!

**Comment by Aiuspaktyn** [comment]
Hi, I can't reproduce, it's a Crashlytics report:

[com.aiuspaktyn.spyrecorderpro_issue_24_crash_59C79A680266000134AE709DEAC2D206_b4e43eada11d11e7896d56847afe9799_0_v2.txt](https://github.com/dropbox/dropbox-sdk-java/files/1332160/com.aiuspaktyn.spyrecorderpro_issue_24_crash_59C79A680266000134AE709DEAC2D206_b4e43eada11d11e7896d56847afe9799_0_v2.txt)

Thanks!

**Comment by greg-db** [comment]
Thanks! I haven't seen this one so we'll have to investigate further. Can you share the code that triggers it though?

**Comment by adityaflexsin** [comment]
Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at com.dropbox.core.android.DbxOfficialAppConnector.getDropboxAppPackage(Unknown Source)
       at com.dropbox.core.android.AuthActivity$3.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by greg-db** [comment]
@adityaflexsin Please share the code that triggers this. Also, have you been able to reproduce this yourself? If so, please let us know the steps to do so. Thanks!
