### ISSUE TITLE
Token request URL 

### ISSUE THREAD

**Issue by dAti** [dropbox/dropbox-sdk-java#155]
As testing out the Dropbox API i can get an authorization code (after consent screen) but when trying to get some tokens I see that the URL https://api.dropboxapi.com/oauth2/token is used , however it's not accessible from my side. Is there any problem with the endpoint ?

Example code : 

```
public OAuthCredentials getOAuthCredentials(String authorizationCode) {
	FileHostingClientCredentials fileHostingClientCredentials = getFileHostingCredentials();
	DbxWebAuth dbxWebAuth = new DbxWebAuth(getDbxRequestConfig(), getDbxAppInfo(fileHostingClientCredentials));
	String accessToken;
	try {
		DbxAuthFinish authFinish = dbxWebAuth.finishFromCode(authorizationCode);
		accessToken = authFinish.getAccessToken();
	} catch (DbxException e) {
		throw new RuntimeException("Error getting access token from Dropbox:" + e);
	}
	
	OAuthCredentials oAuthCredentials = new OAuthCredentials();
	oAuthCredentials.setAccessToken(accessToken);

	return oAuthCredentials;
}
```

**Comment by greg-db** [comment]
This endpoint is accessible and working properly for me. Can you share the full error/output you're getting? Thanks in advance!

**Comment by dAti** [comment]
When I want to access  https://api.dropboxapi.com/oauth2/token my browser (Chrome)  it's saying : 

```
This site can’t be reached

The webpage at https://api.dropboxapi.com/oauth2/token might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE
```

This error comes via an IP from Germany , in Belgium I have the same error.

However https://api.dropboxapi.com is working fine

The error output I am getting  

`Caused by: java.lang.RuntimeException: Error getting access token from Dropbox with authentication code :e2SDCkNjJtAAAAAAAAAANWtwAgRlN8dGuPxPUP2PgaM:com.dropbox.core.NetworkIOException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at be.isabel.zoomit.filehostingadapter.service.dropbox.DropboxAdapter.getOAuthCredentials(DropboxAdapter.java:93)
	at be.isabel.zoomit.filehostingadapter.service.common.FileHostingService.getOAuthCredentials(FileHostingService.java:33)
	at be.isabel.zoomit.filehostingadapter.service.common.FileHostingService$Proxy$_$$_WeldClientProxy.getOAuthCredentials(Unknown Source)
	at be.isabel.zoomit.filehostingadapter.web.FileHostingResource.getOAuthCredentials(FileHostingResource.java:52)
	at be.isabel.zoomit.filehostingadapter.web.FileHostingResource$Proxy$_$$_WeldClientProxy.getOAuthCredentials(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	... 42 more`

**Comment by dAti** [comment]
Thanks for the feedback. It was an internal issue with certificates , used OkHttpRequestor together with a custom keystore , working fine now !
