### ISSUE TITLE
Equivalent of createTemporaryDirectUrl(path)  in  Dropbox sdk API Version 2

### ISSUE THREAD

**Issue by goxr3plus** [dropbox/dropbox-sdk-java#166]
I am trying to find an equivalent of : 

``` JAVA
DbxClientV1 clientV1 = new DbxClientV1(config, ACCESS_TOKEN);
System.out.println(clientV1.createTemporaryDirectUrl("path").url);
```
cause it is producing 

```XML

Exception in thread "main" com.dropbox.core.BadRequestException: {"error": "v1_r
etired"}
	at com.dropbox.core.DbxRequestUtil.unexpectedStatus(DbxRequestUtil.java:298)
	at com.dropbox.core.DbxRequestUtil.unexpectedStatus(DbxRequestUtil.java:285)
	at com.dropbox.core.v1.DbxClientV1$17.handle(DbxClientV1.java:1961)
	at com.dropbox.core.v1.DbxClientV1$17.handle(DbxClientV1.java:1955)
	at com.dropbox.core.DbxRequestUtil.finishResponse(DbxRequestUtil.java:461)
	at com.dropbox.core.DbxRequestUtil$2.run(DbxRequestUtil.java:454)
	at com.dropbox.core.DbxRequestUtil.runAndRetry(DbxRequestUtil.java:498)
	at com.dropbox.core.DbxRequestUtil.doPostNoAuth(DbxRequestUtil.java:450)
	at com.dropbox.core.DbxRequestUtil.doPost(DbxRequestUtil.java:439)
	at com.dropbox.core.v1.DbxClientV1.doPost(DbxClientV1.java:2229)
	at com.dropbox.core.v1.DbxClientV1.createTemporaryDirectUrl(DbxClientV1.java:19
55)
	at main.java.com.goxr3plus.xr3player.remote.dropbox.Dropbox.main(Dropbox.java:5
5)
```
API Version 2 is very very limiting , can't use API Version 1 cause it is retired , what to do > :)

**Comment by jiuyangzhao** [comment]
Hey, thank you for your work on Dropbox API migration.

For `createTemporaryDirectUrl` the V2 version is [`/2/files/get_temporary_link`](https://www.dropbox.com/developers/documentation/http/documentation#files-get_temporary_link) according to our [migration guide](https://www.dropbox.com/developers/reference/migration-guide).

So you can directly call this endpoint from our V2 client.

**Comment by goxr3plus** [comment]
I have desktop applications , so i have to write the Java code for this ?

![dropbox-aoauth2](https://user-images.githubusercontent.com/20374208/32873462-e53aa16e-ca94-11e7-97c1-fe63a33a706d.png)

**Comment by goxr3plus** [comment]
I have one more question , i need directly the link to the Media like i did with V1 Version of Dropbox API -> 

``` https://www.dropbox.com/developers-v1/core/docs#media ```

is there a workaround ?

**Comment by greg-db** [comment]
That's correct, the v2 equivalent of [`createTemporaryDirectUrl`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v1/DbxClientV1.html#createTemporaryDirectUrl-java.lang.String-) is [`getTemporaryLink`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#getTemporaryLink-java.lang.String-).

The v1 [`createTemporaryDirectUrl`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v1/DbxClientV1.html#createTemporaryDirectUrl-java.lang.String-)  method [itself actually does use](https://github.com/dropbox/dropbox-sdk-java/blob/43efdce18cd84ee1d35dad0b1a5d9fa75934db35/src/main/java/com/dropbox/core/v1/DbxClientV1.java#L1953) [/1/media](https://www.dropbox.com/developers-v1/core/docs#media ). We recommend using the method in the SDK, but if you need to call it directly for whatever reason, the v2 equivalent used by [`getTemporaryLink`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#getTemporaryLink-java.lang.String-) is [/2/files/get_temporary_link](https://www.dropbox.com/developers/documentation/http/documentation#files-get_temporary_link).
