### ISSUE TITLE
Unable to instantiate activity 

### ISSUE THREAD

**Issue by rawat-amardeep** [dropbox/dropbox-sdk-java#171]
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.xyz/com.xyz.activity.SplashActivity}: java.lang.ClassNotFoundException: Didn't find class "com.xyz.activity.SplashActivity" on path: DexPathList[[zip file "/data/app/com.xyz-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.xyz-2, /vendor/lib, /system/lib, /lib]]

Dropbox is leading to crashes when running below API level 20. it crashed on 4.4.2 too (HTC).Please advice till which version it is supported. considering the usage the support at least should go till API level 15

The version i am using is

    compile 'com.dropbox.core:dropbox-core-sdk:3.0.5'

I thought about putting a build version check for devices below 20 but i am even not able to integrate it as mere adding the dependency is leading to build crash when the application run on version below 20.

**Comment by greg-db** [comment]
The API v2 Java SDK should support Android level 19+. Android v4.4.2 should be level 19 though, so that should work. Level 19 is working for me in the emulator. Are you seeing crashes on level 19? Is it only crashing on that particular device?

I'll also send this along as a request for support for 15+, but I can't promise if or when that would be implemented.

**Comment by rawat-amardeep** [comment]
I have tested it on a range of kit-kat devices. hence cant consider it as a device specific issue

1. HTC 820G desire plus (4.4.2)
2. Samsung Tab SM-T211( 4.4.2)
3. Samsung Tab SM-T231( 4.4.2)
4. LG X147 (4.4.2)
5. SAMSUNG NOTE 2(GT170) OS version (4.4.2)

Coming on to kit-kat it still run on 14% of devices. further more for the app that want to support till API level 15 should also be able to integrate it at least. it can continue to run post 19 but this should not make such app disable to integrate it at all. there can be build version check stating message like "drop-box not supported" for older version than 19 instead of app getting crashed as soon as they add the dependency in the project.Considering drop box as a widely used integration it should have a reach to larger audience.
Please let me know how soon this can be fixed as support at least till 19 should  work.

**Comment by cakoose** [comment]
The error message refers to "com.xyz.activity.SplashActivity", which is not part of the Dropbox SDK.

Do you have a more detailed error message (e.g. a stack trace) that explains the problem with the Dropbox SDK?

**Comment by rawat-amardeep** [comment]
Yes, It a loader issue created once you add the Dropbox SDK. None of the class files are found on DEX path list.  As soon as the Dropbox dependency is added. the build crashes for API level below 20.
The same is happening with the android demo available in the Dropbox SDK.  
As splash is the entry point in my app. the crash mention the very specific activity in logs. Even if we change it to any other activity the same thing happens. 
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.xyz/com.xyz.activity.SplashActivity}: java.lang.ClassNotFoundException: Didn't find class "com.xyz.activity.SplashActivity" on path: DexPathList[[zip file "/data/app/com.xyz-3.apk"],nativeLibraryDirectories=[/data/app-lib/com.xyz-3, /vendor/lib, /system/lib, /lib]]
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2303)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2458)
                                                                  at android.app.ActivityThread.access$900(ActivityThread.java:172)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:146)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5598)
                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:515)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                  at dalvik.system.NativeStart.main(Native Method)
                                                               Caused by: java.lang.ClassNotFoundException: Didn't find class "com.xyz.activity.SplashActivity" on path: DexPathList[[zip file "/data/app/com.xyz-3.apk"],nativeLibraryDirectories=[/data/app-lib/com.xyz-3, /vendor/lib, /system/lib, /lib]]
                                                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                  at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2294)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2458) 
                                                                  at android.app.ActivityThread.access$900(ActivityThread.java:172) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:146) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5598) 
                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                  at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
                                                                  at dalvik.system.NativeStart.main(Native Method) **

**Comment by rawat-amardeep** [comment]
I added following in my root build. gradle. what does this dependency do?
 classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.5.2'

 On adding following in build. gradle file  it worked for the drop-box sample
  packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
    }

    lintOptions {
        disable 'InvalidPackage'
        abortOnError false
    }

apply plugin: 'com.getkeepsafe.dexcount'

dexcount {
    format = "list"
    includeClasses = true
    includeFieldCount = false
    orderByMethodCount = true
}

will it only work for gradle version 2.10  as i am still facing issue with this new added plugin on gradle version 2.3.3

**Comment by greg-db** [comment]
[The Dropbox Java SDK Android Sample app](https://github.com/dropbox/dropbox-sdk-java/tree/master/examples/android), as provided, should work on Android level 19. That works for me. Is that the actual output you get when trying to run the sample app on Android 19, without modifying it? As Kannan noted, the output you shared doesn't actually mention Dropbox.

The [dexcount-gradle-plugin](https://github.com/KeepSafe/dexcount-gradle-plugin) dependency is a "Gradle plugin to report the number of method references in your APK on every build."
