### ISSUE TITLE
AuthFlow fails with error "missing field account_id"

### ISSUE THREAD

**Issue by wazhar** [dropbox/dropbox-sdk-java#196]
DbxWebAuth.finishFromRedirect always throws BadResponseException.

Affected versions:
3.0.8, 3.0.7, 3.0.6

Version 3.0.5 and below works fine. 
I am guessing this issue has to do with https://github.com/dropbox/dropbox-sdk-java/issues/149

Below is the stacktrace:

com.dropbox.core.BadResponseException: error in response JSON: 1.1: missing field "account_id"
	at com.dropbox.core.DbxRequestUtil.readJsonFromResponse(DbxRequestUtil.java:410)
	at com.dropbox.core.DbxWebAuth$1.handle(DbxWebAuth.java:414)
	at com.dropbox.core.DbxWebAuth$1.handle(DbxWebAuth.java:408)
	at com.dropbox.core.DbxRequestUtil.finishResponse(DbxRequestUtil.java:480)
	at com.dropbox.core.DbxRequestUtil$2.run(DbxRequestUtil.java:473)
	at com.dropbox.core.DbxRequestUtil.runAndRetry(DbxRequestUtil.java:517)
	at com.dropbox.core.DbxRequestUtil.doPostNoAuth(DbxRequestUtil.java:469)
	at com.dropbox.core.DbxWebAuth.finish(DbxWebAuth.java:401)
	at com.dropbox.core.DbxWebAuth.finishFromRedirect(DbxWebAuth.java:379)

Thanks

**Comment by wazhar** [comment]
It seems "account_id" is an optional field. In case of enterprise/team API "team_id" will replace "account_id". 

According to API Documentation: 
RETURNS : A JSON-encoded dictionary including an access token (access_token), token type (token_type), an API v2 user ID (account_id), or if team-linked, an API v2 team ID (team_id) instead.

https://www.dropbox.com/developers/documentation/http/documentation#oa2-token

Thanks.

**Comment by greg-db** [comment]
Thanks! I'll ask the team to get that fixed up.

**Comment by wazhar** [comment]
Any update ?   

Thanks

**Comment by greg-db** [comment]
I don't have an update on this yet. I'll follow up here once I do.

**Comment by sdumont2** [comment]
I made a fix/pull request for this, which would also include the team_id field.

This is working for me.

**Comment by wazhar** [comment]
could someone please merge the fix ?

**Comment by greg-db** [comment]
@wazhar Thanks for following up. I'll ask the team to get this merged and released.

**Comment by greg-db** [comment]
This is fixed in [v3.0.9](https://github.com/dropbox/dropbox-sdk-java/releases/tag/v3.0.9).
