### ISSUE TITLE
sharing().createSharedLinkWithSettings throws JsonToken.isStructEnd()Z error

### ISSUE THREAD

**Issue by Mahdi-Roozbahani** [dropbox/dropbox-sdk-java#197]
I instantiated my dropbox like this:

`        config = DbxRequestConfig.newBuilder("MyAppEngineApp/1.0")
        		.withHttpRequestor(new GoogleAppEngineRequestor())
                .build();
        client = new DbxClientV2(config, ACCESS_TOKEN);`

when I call the following code, it throws me an error:
`SharedLinkMetadata slm = client.sharing().createSharedLinkWithSettings(metadata.getPathLower());`

The temporary link works for me, but the sharing not:
The following one works:
`client.files().getTemporaryLink(metadata.getPathLower());`
When I check metadata variable, every field in this variable related to the sharing is empty. I've been scratching my head for 2 days, I haven't been able to solve it. I am using GAE.

(NOTE: when I look at that specific file in my DropBox account, the link is already created for that file)

This is the more detail error:
`java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonToken.isStructEnd()Z
	at com.dropbox.core.stone.StoneSerializer.skipFields(StoneSerializer.java:129)
	at com.dropbox.core.v2.sharing.ResolvedVisibility$Serializer.deserialize(ResolvedVisibility.java:130)
	at com.dropbox.core.v2.sharing.ResolvedVisibility$Serializer.deserialize(ResolvedVisibility.java:61)
	at com.dropbox.core.stone.StoneSerializers$NullableSerializer.deserialize(StoneSerializers.java:248)
	at com.dropbox.core.v2.sharing.LinkPermissions$Serializer.deserialize(LinkPermissions.java:295)
	at com.dropbox.core.v2.sharing.LinkPermissions$Serializer.deserialize(LinkPermissions.java:248)
	at com.dropbox.core.stone.StructSerializer.deserialize(StructSerializer.java:21)
	at com.dropbox.core.v2.sharing.FileLinkMetadata$Serializer.deserialize(FileLinkMetadata.java:538)
	at com.dropbox.core.v2.sharing.SharedLinkMetadata$Serializer.deserialize(SharedLinkMetadata.java:499)
	at com.dropbox.core.v2.sharing.SharedLinkMetadata$Serializer.deserialize(SharedLinkMetadata.java:386)
	at com.dropbox.core.stone.StructSerializer.deserialize(StructSerializer.java:21)
	at com.dropbox.core.stone.StoneSerializer.deserialize(StoneSerializer.java:66)
	at com.dropbox.core.v2.DbxRawClientV2$1.execute(DbxRawClientV2.java:125)
	at com.dropbox.core.v2.DbxRawClientV2.executeRetriable(DbxRawClientV2.java:300)`

**Comment by greg-db** [comment]
Thanks for the report. Can you let me know:
- the version number of the Dropbox Java library you have installed
- the version number of the Jackson library you have installed
- how you're installing the libraries (e.g., Graven, Maven, or directly adding .jar; see: #145)
- if this also happens off of GAE or not, if you can try
- if you're using Proguard, and what your config looks like if so

**Comment by jiuyangzhao** [comment]
@Mahdi-Roozbahani isStructEnd() should be there in 2.6.4 I'm not sure why we are seeing that error.

I just tried to to compile the java sdk with 2.6.4 it won't even compile. If possible I suggest you upgrade. I will run some test in maven later to figure out why that happened.

**Comment by Mahdi-Roozbahani** [comment]
After many days, I think I figured out what the problem was. Something was messed up with my appengine loaclhost. I removed my appengine local host and created a new one, and the problem got fixed. This was so annoying, I still don't why this problem was happening.

**Comment by greg-db** [comment]
Thanks for following up. My apologies for the trouble, but I'm glad to hear this was resolved.
