### ISSUE TITLE
NPE DbxRequestUtil.finishReponse doesn't account for null body

### ISSUE THREAD

**Issue by jamie-everlaw** [dropbox/dropbox-sdk-java#213]
```
java.lang.NullPointerException
        at com.dropbox.core.util.IOUtil.closeInput(IOUtil.java:129)
        at com.dropbox.core.DbxRequestUtil.finishResponse(DbxRequestUtil.java:482)
        at com.dropbox.core.DbxRequestUtil$2.run(DbxRequestUtil.java:473)
        at com.dropbox.core.DbxRequestUtil.runAndRetry(DbxRequestUtil.java:517)
        at com.dropbox.core.DbxRequestUtil.doPostNoAuth(DbxRequestUtil.java:469)
        at com.dropbox.core.DbxWebAuth.finish(DbxWebAuth.java:401)
        at com.dropbox.core.DbxWebAuth.finishFromCode(DbxWebAuth.java:309)
```
`finishReponse` has the line `IOUtil.closeInput(response.getBody());`, but we had an instance where `getBody()` returned null.

**Comment by cakoose** [comment]
Hmm, there's a bunch of code that assumes `response.getBody()` will not be null.

One hacky fix is to replace null response bodies with an empty one.  A more "proper" fix would be to make sure everyone who needs a response body checks for null.

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by jamie-everlaw** [comment]
@handstandsam What do you mean by example? I provided part of the stack trace that involves this sdk.

**Comment by handstandsam** [comment]
Thanks for replying back.  We went through and were cleaning up old issues this week.

I see where you are taking about here:
https://github.com/dropbox/dropbox-sdk-java/blob/d77cc3ee09e13643605b3eb3f5706dd86de987f3/dropbox-sdk-java/src/main/java/com/dropbox/core/DbxRequestUtil.java#L515-L521

We can wrap these in a null check for our next version `5.4.0` that we're planning on releasing next week.  Thank you!

**Comment by jamie-everlaw** [comment]
Great, thanks!
