### ISSUE TITLE
Can't upload files 

### ISSUE THREAD

**Issue by damionx7** [dropbox/dropbox-sdk-java#256]
I get this error in AndroidStudio while I try to upload any file

` E/org.eu.thedoc.shelper.studyhelper.dropbox.FilesDropboxActivity: Failed to upload file.
    com.dropbox.core.NetworkIOException: Pipe closed
        at com.dropbox.core.DbxUploader.finish(DbxUploader.java:275)
        at com.dropbox.core.DbxUploader.uploadAndFinish(DbxUploader.java:126)
        at com.dropbox.core.DbxUploader.uploadAndFinish(DbxUploader.java:96)
        at com.dropbox.core.v2.DbxUploadStyleBuilder.uploadAndFinish(DbxUploadStyleBuilder.java:92)
        at org.eu.thedoc.shelper.studyhelper.dropbox.UploadDropboxFilesTask.doInBackground(UploadDropboxFilesTask.java:66)
        at org.eu.thedoc.shelper.studyhelper.dropbox.UploadDropboxFilesTask.doInBackground(UploadDropboxFilesTask.java:22)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.io.IOException: Pipe closed
        at java.io.PipedInputStream.read(PipedInputStream.java:319)
        at java.io.PipedInputStream.read(PipedInputStream.java:394)
        at okio.Okio$2.read(Okio.java:140)
        at okio.RealBufferedSink.writeAll(RealBufferedSink.java:105)
        at com.dropbox.core.http.OkHttpUtil$PipedStream.writeTo(OkHttpUtil.java:79)
        at com.dropbox.core.http.OkHttp3Requestor$PipedRequestBody.writeTo(OkHttp3Requestor.java:369)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.android.tools.profiler.agent.okhttp.OkHttp3Interceptor.intercept(OkHttp3Interceptor.java:57)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
`

**Comment by greg-db** [comment]
Can you share the steps and code to reproduce this issue? Also, is there anything on your network connection (e.g., firewall, proxy, etc.) that may be interfering with the connection to the Dropbox API servers? (For uploading files, it would be content.dropboxapi.com:443.)

**Comment by damionx7** [comment]
This worked after using custom OkHttp builder with the dropbox client builder
