### ISSUE TITLE
java.lang.NoClassDefFoundError: com/dropbox/core/json/JsonReader$FileLoadException

### ISSUE THREAD

**Issue by Setekhe** [dropbox/dropbox-sdk-java#258]
I copied all the cope from within the Authorize example into a brand new maven setup (as I dont know how use gradle and am currently running windows with little technical experience) I added the sdk and added ~
<dependency>
	    <groupId>com.dropbox.core</groupId>
	    <artifactId>dropbox-core-sdk</artifactId>
	    <version>3.1.1</version>
</dependency>
to the pom.xml and added the sdk to my maven library. I compile it using mvn package howver when I run it it reports.
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/dropbox/core/json/JsonReader$FileLoadException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.dropbox.core.json.JsonReader$FileLoadException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more

**Comment by Setekhe** [comment]
![Capture213](https://user-images.githubusercontent.com/40688197/62879427-019bbf00-bd23-11e9-9545-92642c482952.PNG)
This is my current dependencies/libraries that I have added.

**Comment by greg-db** [comment]
I'm not sure off hand what the issue may be here, but it looks like it may have more to do with your development environment and Maven setup rather than the Dropbox library itself, so I don't know how much help we can offer.

I also see you also [posted this on StackOverflow though](https://stackoverflow.com/questions/57476037/how-to-fix-exception-in-thread-main-java-lang-noclassdeffounderror-com-dropb) and are getting some help there, so I'll close this in favor of that. Please let us know if there does seem to be an issue with the Dropbox library itself though. Thanks!

**Comment by jiuyangzhao** [comment]
I think the problem locates at how you run your program.

I just created a helloworld project with maven and added this sdk as dependency.

If I do `java -cp target/my_test-1.0-SNAPSHOT.jar HelloWorld`, I got NoClassDefFoundError too.
If I do `mvn exec:java -Dexec.mainClass="HelloWorld"`, it works fine for me.
