### ISSUE TITLE
DbxClient.getAccountInfo throws exception with negative quota_info.shared value 

### ISSUE THREAD

**Issue by ckherrmann** [dropbox/dropbox-sdk-java#28]
Sometimes when I call DbxClient.getAccountInfo(), the DropBox server returns a negative value for "quota_info.shared".  When this happens, the method throws an exception:
com.dropbox.core.DbxException$BadResponse: error in response JSON: 1.250: "quota_info"."shared": expecting a non-negative number, got: -1297260
	at com.dropbox.core.DbxRequestUtil.readJsonFromResponse(DbxRequestUtil.java:222)
	at com.dropbox.core.DbxClient$4.handle(DbxClient.java:284)
	at com.dropbox.core.DbxClient$4.handle(DbxClient.java:279)
	at com.dropbox.core.DbxRequestUtil.doGet(DbxRequestUtil.java:242)
	at com.dropbox.core.DbxClient.doGet(DbxClient.java:1942)
	at com.dropbox.core.DbxClient.getAccountInfo(DbxClient.java:279)

I am using dropbox core sdk 1.7.7, but the latest seems to have the same problem with assuming that the "shared" value must be unsigned.

**Comment by krieb** [comment]
Hi @ckherrmann,

This was a result of a bug on the server side.  The bug has been fixed and should be released sometime Friday (Jan 21, 2016) evening (Pacific Time).

After the release, you should no longer see this exception occur.  Please re-open this issue if you continue to see an error at any point after Friday.
