### ISSUE TITLE
Fatal Exception: com.dropbox.core.v2.filerequests.analytics.LicenseCheckError$LicenseServiceError: Could not bind with the licensing service

### ISSUE THREAD

**Issue by hexise** [dropbox/dropbox-sdk-java#312]
Hello,

I received some crash reports in my Android app crashlytics system, related to dropbox licensing service, how can I fix this problem? I just changed my app from apk to app bundle and enabled google play integrity protected, is that the problem to this issue? I am using com.dropbox.core:dropbox-core-sdk:3.1.5, thanks. 

Fatal Exception: com.dropbox.core.v2.filerequests.analytics.LicenseCheckError$LicenseServiceError: Could not bind with the licensing service
       at com.dropbox.core.v2.filerequests.analytics.LicenseClient.connectToLicensingService(LicenseClient.java:108)
       at com.dropbox.core.v2.filerequests.analytics.LicenseClient.bridge$lambda$0$LicenseClient(LicenseClient.java)
       at com.dropbox.core.v2.filerequests.analytics.LicenseClient$$Lambda$1.run(LicenseClient.java)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6517)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by greg-db** [comment]
I see this seems to be throwing an exception from `com.dropbox.core.v2.filerequests`, but these classes and this error message aren't actually written by Dropbox as far as I can tell. There [isn't a `com.dropbox.core.v2.filerequests.analytics` in the actual Dropbox SDK](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/). It looks like this might be related to [Android's licensing](https://developer.android.com/google/play/licensing/client-side-verification#java)? That being the case we can't offer help for that. You'll need to refer to the Android documentation/support instead.

**Comment by hexise** [comment]
Thank you for the clarification.
