### ISSUE TITLE
java.net.SocketTimeoutException when file is around 100 MB

### ISSUE THREAD

**Issue by NLLAPPS** [dropbox/dropbox-sdk-java#32]
Eror is:
W/System.err: com.dropbox.core.DbxException$NetworkIO: java.net.SocketTimeoutException: timeout
W/System.err:     at com.dropbox.core.DbxUploader.finish(DbxUploader.java:50)

Is it possible to provide a method to set connection time-out?

**Comment by cakoose** [comment]
Are there more lines in the stack trace?  If so, can you include those as well?

Ideally, we want our timeouts to trigger when there is no network activity for a while.  We don't want to enforce an absolute time limit for all API calls because (obviously) some API calls are expected to take much longer than others.

Two options for workarounds:
1. Subclass `StandardHttpRequestor` and override the `configureConnection` method to set a longer timeout.  Then pass your customized `StandardHttpRequestor` instance to the DbxClientV2 constructor.
2. Upload the file in chunks of 4 MB or 8 MB using `uploadSessionStart`, `uploadSessionAppend` and `uploadSessionFinish`.  Uploading in chunks has another advantage: when there are transient network errors, you can try again by resuming from the last chunk instead of starting from the beginning.  Of course, this requires more book-keeping on your end.

**Comment by NLLAPPS** [comment]
Thank you. I was using okhttp so I have extended OkHttpRequestor from SDK and created ExtendedOkHttpRequestor 

```java
public class ExtendedOkHttpRequestor extends OkHttpRequestor {
    public static String TAG = "ExtendedOkHttpRequestor";
    public static final int extendedTimeout = 50 * 1000;
    public static final OkHttpRequestor Instance = new OkHttpRequestor(longOkHttpClient());

    public ExtendedOkHttpRequestor(com.squareup.okhttp.OkHttpClient client) {
        super(client);
    }

    //Bypass  OkHttpRequestor to increase upload timeout
    private static OkHttpClient longOkHttpClient() {
        if (CloudUtils.DEBUG) {
            CloudUtils.getInstance().sendLog(TAG, "creating longOkHttpClient");
        }
        OkHttpClient client = new OkHttpClient();
        client.interceptors().add(new DropboxLoggingInterceptor());
        client.setConnectTimeout(DefaultTimeoutMillis, TimeUnit.MILLISECONDS);
        client.setReadTimeout(DefaultTimeoutMillis, TimeUnit.MILLISECONDS);
        client.setWriteTimeout(extendedTimeout, TimeUnit.MILLISECONDS);
        return client;
    }
}
```
Plugged it with 

```java
DbxRequestConfig requestConfig = new DbxRequestConfig(
                    "example-cloud",
                    Locale.getDefault().toString(),
                    ExtendedOkHttpRequestor.Instance);
```
Yet received same error.

```plain
01-05 10:06:18.819 16047-18478/com.example D/CLOUD_DropboxLoggingInterceptor: Sending request https://api-content.dropbox.com/2-beta-2/files/upload on null
                                                                              Authorization: Bearer xxxx
                                                                              Content-Type: application/octet-stream
                                                                              User-Agent: example-cloud Dropbox-Java-SDK/2.0-beta-4
                                                                              Dropbox-API-Arg: {"path":"/0442_333_2016_01_02_16_02_05.wav","mode":{".tag":"overwrite"},"autorename":false,"mute":false}


01-05 10:06:58.149 16047-18478/com.example W/System.err: com.dropbox.core.DbxException$NetworkIO: java.net.SocketTimeoutException: timeout
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.dropbox.core.DbxUploader.finish(DbxUploader.java:50)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.dropbox.core.v2.DbxUploadStyleBuilder.run(DbxUploadStyleBuilder.java:31)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.examplecloud.dropbox.DropBoxHelper.upload(DropBoxHelper.java:56)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.examplecloud.DropboxClient.upload(DropboxClient.java:124)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.examplecloud.DroboxV2IntentService.processQueue(DroboxV2IntentService.java:98)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.examplecloud.BaseIntentService.processIntent(BaseIntentService.java:114)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.examplecloud.BaseIntentService.onHandleIntent(BaseIntentService.java:51)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at android.os.Looper.loop(Looper.java:145)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
01-05 10:06:58.149 16047-18478/com.example W/System.err: Caused by: java.net.SocketTimeoutException: timeout
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at okio.Okio$3.newTimeoutException(Okio.java:207)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at okio.AsyncTimeout.exit(AsyncTimeout.java:250)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:79)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:909)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.access$300(HttpEngine.java:93)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:894)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:748)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.squareup.okhttp.Call.getResponse(Call.java:277)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:234)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.examplecloud.DropboxLoggingInterceptor.intercept(DropboxLoggingInterceptor.java:21)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:223)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:196)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.squareup.okhttp.Call.execute(Call.java:79)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.dropbox.core.http.OkHttpRequestor$BufferUploader.finish(OkHttpRequestor.java:137)
01-05 10:06:58.149 16047-18478/com.example W/System.err:     at com.dropbox.core.DbxUploader.finish(DbxUploader.java:38)
01-05 10:06:58.149 16047-18478/com.example W/System.err: 	... 10 more
```

Note the difference it took only 40 seconds to upload, am I missing something?

**Comment by NLLAPPS** [comment]
By the way, file uploads fine

**Comment by NLLAPPS** [comment]
Eror gone away once I have increased time-out on connection, read and write.

**Comment by MrThiago** [comment]
The one I manage was like this:

```
        //New Request
        HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
        logging.setLevel(HttpLoggingInterceptor.Level.BASIC);
        final OkHttpClient client = new OkHttpClient.Builder()
                .addInterceptor(logging)
                .connectTimeout(30, TimeUnit.SECONDS)
                .readTimeout(30, TimeUnit.SECONDS)
                .writeTimeout(30, TimeUnit.SECONDS)
                .build();
```
