### ISSUE TITLE
/list_folder/longpoll throws Exception

### ISSUE THREAD

**Issue by ranapnea** [dropbox/dropbox-sdk-java#35]
Calling DbxFiles.listFolderLongpoll throws exception:

com.dropbox.core.DbxException$BadRequest: Error in call to API function "files/list_folder/longpoll": Your request includes an Authorization header, but this function does not use it.
                                                                       at com.dropbox.core.DbxRequestUtil.unexpectedStatus(DbxRequestUtil.java:262)
                                                                       at com.dropbox.core.v2.DbxRawClientV2.rpcStyle(DbxRawClientV2.java:95)
                                                                       at com.dropbox.core.v2.DbxFiles.listFolderLongpoll(DbxFiles.java:7678)
                                                                       at com.dropbox.core.v2.DbxFiles.listFolderLongpoll(DbxFiles.java:7705)

**note**: Looking at the source code, it seems indeed that listFolderLongpoll includes access token in the request which this is contrary to docs for /list_folder/longpoll endpoint.

**Comment by krieb** [comment]
The latest release (2.0-beta-5) should have a fix for this.  Let me know if you still see an issue.
