### ISSUE TITLE
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by gemiren** [dropbox/dropbox-sdk-java#57]
Got the following exception when uploading to Dropbox. Using the latest 2.0.4 SDK. Any help is appreciated. Thanks.

Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103)
at com.android.okhttp.Connection.connect(Connection.java:143)
at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
at com.dropbox.core.http.StandardHttpRequestor$Uploader.getOutputStream(StandardHttpRequestor.java:108)
at com.dropbox.core.http.StandardHttpRequestor$Uploader.<init>(StandardHttpRequestor.java:99)
at com.dropbox.core.http.StandardHttpRequestor.startPost(StandardHttpRequestor.java:71)
at com.dropbox.core.http.StandardHttpRequestor.startPost(StandardHttpRequestor.java:26)
at com.dropbox.core.DbxRequestUtil.startPostRaw(DbxRequestUtil.java:219)

**Comment by kuffs** [comment]
Yes me too.

**Comment by jacobras** [comment]
Same here. For those of you new to the Dropbox SDK: version 2.0.3 does not have this issue, so I would use that until a new version is released.

**Comment by krieb** [comment]
@gemiren @jacobras @kuffs 

This was a fun one. Turns out Java 7+ will properly parse a PEM encoded file. The Javadoc states it handles DER encoded binary files, but that it can also handle Base64-encoded DER bounded with `----- BEGIN CERTIFICATE -----` and `----- END CERTIFICATE -----`. The Base64-encoded variant is essentially PEM encoding.

Oracle JRE 7+ will handle the PEM encoded files properly. However, Android seems to have issues with it. Unlike Oracle JRE 6, Android will not raise an error during parsing. Instead, it seems to silently fail parsing the PEM encoded file, omitting the required certificates to validate the chain. I didn't catch it earlier since the `OkHttpRequestor` used by the Android example doesn't pin certs like the `StandardHttpRequestor` does.

The fix will be released in **2.0.5** and I will add a task to enable certificate pinning `OkHttpRequestor`.

**Comment by gemiren** [comment]
Any ETA on the 2.0.5? Thanks.

**Comment by krieb** [comment]
@gemiren 2.0.5 is scheduled for release this week. I can't give you an exact date, but most likely it will be released tomorrow (06/08/2016).

**Comment by krieb** [comment]
Version **2.0.5** is out. Re-open if you continue to see this issue.

**Comment by jacobras** [comment]
Seems to work fine, thank you! Will start rolling out an update for my app including version 2.0.5 of the Dropbox SDK in a week. If any problems arise I will send my feedback.
