### ISSUE TITLE
ListFolderBuilder's start() throws empty ServerException

### ISSUE THREAD

**Issue by jacobras** [dropbox/dropbox-sdk-java#61]
I'm getting error reports from a user. My code (using the latest version of the SDK, 2.0.5):

```java
final ListFolderBuilder folderBuilder = mDbxClient.files()
        .listFolderBuilder("")
        .withRecursive(true);
return folderBuilder.start();
```

The error report:
```
com.dropbox.core.ServerException: 
       at [..]
Caused by com.dropbox.core.ServerException
       at com.dropbox.core.DbxRequestUtil.unexpectedStatus(DbxRequestUtil.java:296)
       at com.dropbox.core.v2.DbxRawClientV2$1.execute(DbxRawClientV2.java:107)
       at com.dropbox.core.v2.DbxRawClientV2.executeRetriable(DbxRawClientV2.java:252)
       at com.dropbox.core.v2.DbxRawClientV2.rpcStyle(DbxRawClientV2.java:97)
       at com.dropbox.core.v2.files.DbxUserFilesRequests.listFolder(DbxUserFilesRequests.java:629)
       at com.dropbox.core.v2.files.ListFolderBuilder.start(ListFolderBuilder.java:109)
       [..]
```

It looks like the message for the ServerException is empty. Any idea what could happen here? The user reported that even after reinstalling the issue continues to occur. The user verified that the app is still linked. This happens on a HTC One running Android 5.0.2.

If it helps I can send the request ID (the one DbxException holds), but I do not want to post it here in public.

**Comment by greg-db** [comment]
Thanks for the report! I can't seem to reproduce this myself, so it sounds like it's account-specific.

That being the case, please open an API ticket with the user ID so we can look into it specifically:

https://www.dropbox.com/developers/contact

Thanks in advance!
