### ISSUE TITLE
"No authentication challenges found" during listFolderContinue()

### ISSUE THREAD

**Issue by jacobras** [dropbox/dropbox-sdk-java#62]
I've been getting these error reports:

```java
Caused by com.dropbox.core.w: No authentication challenges found
   at com.dropbox.core.DbxRequestUtil.startPostRaw(DbxRequestUtil.java:238)
   at com.dropbox.core.v2.DbxRawClientV2$1.execute(DbxRawClientV2.java:100)
   at com.dropbox.core.v2.DbxRawClientV2.addAuthHeaders(DbxRawClientV2.java:252)
   at com.dropbox.core.v2.DbxRawClientV2.addAuthHeaders(DbxRawClientV2.java:97)
   at com.dropbox.core.v2.files.DbxUserFilesRequests.listFolderContinue(DbxUserFilesRequests.java:688)
   at com.dropbox.core.v2.files.DbxUserFilesRequests.listFolderContinue(DbxUserFilesRequests.java:716)
   [..]
Caused by java.io.IOException: No authentication challenges found
   at libcore.net.http.HttpURLConnectionImpl.getAuthorizationCredentials(HttpURLConnectionImpl.java:436)
   at libcore.net.http.HttpURLConnectionImpl.processAuthHeader(HttpURLConnectionImpl.java:416)
   at libcore.net.http.HttpURLConnectionImpl.processResponseHeaders(HttpURLConnectionImpl.java:365)
   at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:301)
   at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:495)
   at libcore.net.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:134)
   at com.dropbox.core.http.StandardHttpRequestor.toResponse(StandardHttpRequestor.java:49)
   at com.dropbox.core.http.StandardHttpRequestor.access$000(StandardHttpRequestor.java:28)
   at com.dropbox.core.http.StandardHttpRequestor$Uploader.finish(StandardHttpRequestor.java:157)
   at com.dropbox.core.DbxRequestUtil.startPostRaw(DbxRequestUtil.java:233)
   at com.dropbox.core.v2.DbxRawClientV2$1.execute(DbxRawClientV2.java:100)
   at com.dropbox.core.v2.DbxRawClientV2.addAuthHeaders(DbxRawClientV2.java:252)
   at com.dropbox.core.v2.DbxRawClientV2.addAuthHeaders(DbxRawClientV2.java:97)
   at com.dropbox.core.v2.files.DbxUserFilesRequests.listFolderContinue(DbxUserFilesRequests.java:688)
   at com.dropbox.core.v2.files.DbxUserFilesRequests.listFolderContinue(DbxUserFilesRequests.java:716)
   [..]
```

My code:
```java
mDbxClient.files().listFolderContinue(cursor);
```

Any idea what could cause this?

**Comment by greg-db** [comment]
Thanks for the report. We're looking into it.

**Comment by krieb** [comment]
@jacobras Thanks for you patience. Turns out this was an issue on the server-side. We were not sending the `WWW-Authenticate` header back in our 401 responses from APIv2 endpoints. Strict clients will complain about the missing header.

The fix should be out in production now. Let me know if you see any further issues with this.

**Comment by jacobras** [comment]
I'll monitor it, @krieb. Thanks!
