### ISSUE TITLE
ListFolderBuilder's start() throws ServerException when file is moved inside dropbox

### ISSUE THREAD

**Issue by cbumae** [dropbox/dropbox-sdk-java#93]
Maybe related to https://github.com/dropbox/dropbox-sdk-java/issues/61

I am using the version 2.1.2 of the SDK.

I have the following code that is executed in a loop (whenever a change has been detected by a longpoll):
```
ListFolderResult folder = client.files().listFolderBuilder(DIRECTORY)
        .withIncludeDeleted(false)
        .withRecursive(false)
        .start();
```
This code throws the following exception if a file in DIRECTORY is moved outside of DIRECTORY but still inside the dropbox by another client (dropbox PC application):
```
com.dropbox.core.ServerException: 
     at com.dropbox.core.DbxRequestUtil.unexpectedStatus(DbxRequestUtil.java:298)
     at com.dropbox.core.v2.DbxRawClientV2$1.execute(DbxRawClientV2.java:108)
     at com.dropbox.core.v2.DbxRawClientV2.executeRetriable(DbxRawClientV2.java:256)
     at com.dropbox.core.v2.DbxRawClientV2.rpcStyle(DbxRawClientV2.java:97)
     at com.dropbox.core.v2.files.DbxUserFilesRequests.listFolder(DbxUserFilesRequests.java:934)
     at com.dropbox.core.v2.files.ListFolderBuilder.start(ListFolderBuilder.java:109)
```

This is not really critical for my application as this is not a use case for it: I noticed this during testing.

**Comment by greg-db** [comment]
These can be account specific, so please open an API ticket with the affected user ID(s) so we can check on it specifically:

https://www.dropbox.com/developers/contact

Thanks!
